env:
  global:
    - LANG=en_US.UTF-8
language: objective-c
rvm:
  - 2.0.0
before_install:
  - brew update
  - brew upgrade xctool
  - bundle install
install:
  - bundle exec pod update
  - bundle exec pod install
script:
  bash script/build